#--------------------------------------------------------
# File: Makefile    Author(s): Siomon DÉsaulniers
# Date: 2013-12-10
#--------------------------------------------------------
# Makefile pour le rapport du tp#2 du cours INF1010
#--------------------------------------------------------

DOC=rapport

tex:
	pdflatex $(DOC).tex
clean:
	rm -f *.out *.toc *.aux *.log

