.TH inf1010tp2-server 1 2013-11-27
.SH NOM
.B inf1010tp2-server
- Serveur de chat.
.SH SYNOPSYS
.B inf1010tp2-server
[-p \fIport\fP]

.B inf1010tp2-server
[-h]
.SH DESCRIPTION
Serveur de chat réalisé dans le cadre du Travail Pratique #2 du cours
\fBINF1010\fP à l'Université du Québec à Trois-Rivières.
.SH OPTIONS

.TP
.B -p, --port \fIport\fP
Spécifie le port sur lequel le serveur devra écouter.
.TP
.B -h, --help
Affiche un texte d'aide sur la sortie standart (\fBstdout\fP).
.SH AUTEURS
.TP
Écrit par
.IP \(bu
.\} 
Simon Désaulniers <rostydela@gmail.com>
.IP \(bu
.\} 
Frédéric Hamelin <fredhamelin91@gmail.com>
